<?php
$carousel= array(
        1=>array(
            'id' => '1',
            'fecha' => '2022-08-05',
            'categoria' => 'Conferences',
            'titulo' => 'XV Conferencia Trinacional en Defensa de la Educación Pública',
            'enbarra1' => 'XV Conferencia Trinacional en Defensa de la Educación Pública',
            'enbarra2' => 'Oaxaca, México 2022. México / Estados Unidos / Canadá',
            'autor' => 'Coalición trinacional',
            'pais' => 'Mexico',
            'contcorto' => 'Próxima a celebrarse en el estado de Oaxaca durante los días 7, 8 y 9 de octubre de 2022, la quinceava edición de la Conferencia Trinacional en Defensa de la Educación Pública',
            'contlargo' => '<p class="lead">México / Estados Unidos / Canadá        <br>        &nbsp;&nbsp;Próxima a celebrarse en el estado de Oaxaca durante los días 7, 8 y 9 de octubre de 2022, la quinceava edición de la Conferencia Trinacional en Defensa de la Educación Pública, tendrá lugar ante las múltiples preocupaciones que docentes, sindicalistas, investigadores, estudiantes y activistas dentro del sector educativo comparten. Dicho espacio dará lugar a la reflexión y dialogo, tanto de las problemáticas que se vienen profundizando desde antes de la pandemia, como aquellos que se derivan de las dinámicas sociales que la pandemia y su administración de parte de los Estados impusieron a las comunidades educativas.        <br><br>        &nbsp;&nbsp;Contexto bajo el cual diversas personalidades, organizaciones y comunidades educativas en Norteamérica estaremos compartiendo y deliberando las propuestas necesarias para recuperar o profundizar procesos comunitarios, que hoy son fundamentales para enfrentar el contexto que enfrente la educación pública como derecho social y humano.        <br><br>        &nbsp;&nbsp;En breve daremos a conocer la convocatoria y la información correspondiente para que quienes tengan interés puedan participar y acceder a las discusiones, reflexiones y propuestas producto de esta quinceava conferencia.        <br></p>',
            'imagen' => '1663290889.jpg',
            'imagenart' => '1663290889.jpg',
            'imagenlat' => '1663290889.jpg',
        ),
        2=>array(
            'id' => '2',
            'fecha' => '2022-08-01',
            'categoria' => 'Conferences',
            'titulo' => 'Conferencia Nacional de la Sección Mexicana de la Coalición Trinacional en Defensa de la Educación Pública.',
            'enbarra1' => 'Hacia la XV Conferencia Trinacional (México, Estados Unidos, Canadá).',
            'enbarra2' => 'Una educación pública para reconstruir la comunidad',
            'autor' => 'Coalición trinacional',
            'pais' => 'Mexico',
            'contcorto' => 'A las organizaciones sindicales, a los profesores, investigadores, estudiantes, activistas e interesados en defensa de la educación pública como un derecho social a participar en la Conferencia Nacional en Defensa de la Educación Pública 2022,se llevará a cabo del viernes 9 al sábado 10 de septiembre 2022',
            'contlargo' => '<p class="display-6">Hacia la XV Conferencia Trinacional (México, Estados Unidos, Canadá).</p><br>        <p class="lead">        &nbsp;&nbsp;Los sistemas educativos en el mundo han sufrido profundos estragos a consecuencia del cierre de escuelas y el confinamiento producto del COVID-19. Para muchos estudiantes no sólo representó una interrupción temporal en su educación sino un final abrupto para la misma, al incorporarse al trabajo, perder a sus padres o tutores o simplemente no tener las condiciones suficientes para ponerse al corriente en sus aprendizajes. Esta situación ha transgredido el tejido social y educativo afectando a la educación pública en el mundo, y la educación en México no ha sido la excepción.         <br><br>        &nbsp;&nbsp;Mientras tanto los trabajadores de la educación sufrieron transformaciones múltiples en sus condiciones de trabajo y; su práctica docente y profesional, mientras que el aprendizaje en línea exacerbó las desigualdades en educación. Nuestro gobierno no contaba con las políticas, la infraestructura ni los recursos necesarios para desarrollar el aprendizaje en línea de manera que se garantizara que todos los niños y las niñas, jóvenes y universitarios pudieran participar en igualdad de condiciones.          <br><br>        &nbsp;&nbsp;Poco a poco comienza a estabilizarse la pandemia y, en consecuencia, comienza la reapertura de las escuelas y centros educativos a diferentes niveles, no obstante, esta reapertura no deshará el daño provocado en la educación, ni garantizará que todos los niños y jóvenes regresen a la escuela. Puesto que, muchos problemas que observamos hoy en el sector educativo son preexistentes a ella; la vulnerabilidad a la que se enfrentan los niños, familias y comunidades de bajos ingresos, la desigual cobertura en educación, la discriminación y exclusión por raza, clase y género, la precariedad salarial y de condiciones de trabajo de los docentes, entre muchos otros aspectos que durante años hemos denunciado desde la Coalición Trinacional en Defensa de la Educación Pública.        &nbsp;&nbsp;Ante este panorama consideramos necesaria una reflexión que nos permita identificar cuáles son los estragos que la pandemia ha ocasionado en la educación pública en México, así como identificar las acciones indispensables para superar los problemas provocados por ella e identificar las alternativas para reconstruir a las comunidades educativas que han sido afectadas por el distanciamiento social y el auto-centramiento provocado por el confinamiento; al mismo tiempo, necesitamos recuperar las demandas en defensa de la educación pública que apuntan a exigir al gobierno mexicano el cumplimiento de sus responsabilidades como garante del derecho a la educación; por ello:           <br><br>        </p>        <p class="display-6"><b>Convocamos.</b></p><br>        <p class="lead">        &nbsp;&nbsp;A las organizaciones sindicales, a los profesores, investigadores, estudiantes, activistas e interesados en',
            'imagen' => '1663776746.png',
            'imagenart' => '1663776746.png',
            'imagenlat' => '1663776746.png',
        ),
        3=>array(
            'id' => '3',
            'fecha' => '2022-07-28',
            'categoria' => 'Conferences',
            'titulo' => 'Coalición Trinacional en Defensa de la Educación da a conocer folleto en la ANR de la CNTE',
            'enbarra1' => 'Coalición Trinacional en Defensa de la Educación',
            'enbarra2' => 'Da a conocer folleto en la ANR de la CNTE',
            'autor' => 'Coalición trinacional',
            'pais' => 'Mexico',
            'contcorto' => 'folleto "Entre transformaciones y continuidades en el derecho a la educación pública en tiempos de la #4T"',
            'contlargo' => '<p class="lead">"Entre transformaciones y continuidades en el derecho a la educación pública en tiempos de la #4T"<br>        &nbsp;&nbsp;Una comisión de la sección mexicana de la Coalición Trinacional en Defensa de la Educación Pública se hizo presente durante la Asamblea Nacional Representativa de la CNTE, para dar un saludo a los trabajos y compartir el folleto "Entre transformaciones y continuidades en el derecho a la educación pública en tiempos de la #4T". En donde se han recopilado diversos materiales de reflexión y balance político sobre las diversas problemáticas presentes en el sector educativo.</p>',
            'imagen' => '1665036947.jpg',
            'imagenart' => '1665036947.jpg',
            'imagenlat' => '1665037057.jpg',
        ),
)
?>