<?php
$galeria= array(
        1=>array(
            'id' => '1',
            'fecha' => '2022-09-07',
            'categoria' => 'Conferences',
            'titulo' => 'XVCONFERENCIA DE LA COALICIÓN TRINACIONAL EN DEFENSA DE LA EDUCACIÓN PÚBLICA (MÉXICO, ESTADOS UNIDOS Y CANADÁ)',
            'autor' => 'Coalición Trinacional',
            'pais' => 'Mexico',
            'imagen' => '1671853481.jpg',
        ),
        2=>array(
            'id' => '2',
            'fecha' => '2022-09-01',
            'categoria' => 'Conferences',
            'titulo' => 'CONFERENCIA NACIONAL DE LA SECCIÓN MEXICANA DE LA COALICIÓN TRINACIONAL EN DEFENSA DE LA EDUCACIÓN PÚBLICA.',
            'autor' => 'Coalición Trinacional',
            'pais' => 'Mexico',
            'imagen' => '1671853539.png',
        ),
        3=>array(
            'id' => '3',
            'fecha' => '2022-08-05',
            'categoria' => 'Forums',
            'titulo' => 'FORO REGRESO A CLASES PRESENCIALES EN EL CICLO ESCOLAR',
            'autor' => 'Coalición Trinacional',
            'pais' => 'Mexico',
            'imagen' => '1671853592.jpg',
        ),
        4=>array(
            'id' => '4',
            'fecha' => '2022-07-05',
            'categoria' => 'Bells',
            'titulo' => 'COALICIÓN TRINACIONAL EN DEFENSA DE LA EDUCACIÓN DA A CONOCER FOLLETO EN LA ANR DE LA CNTE',
            'autor' => 'Coalición Trinacional',
            'pais' => 'Mexico',
            'imagen' => '1671853402.jpg',
        ),
        5=>array(
            'id' => '5',
            'fecha' => '2022-06-16',
            'categoria' => 'Actions',
            'titulo' => 'SOLIDARIDAD CON LA HUELGA DEL SUTIEMS',
            'autor' => 'Tri-National',
            'pais' => 'Mexico',
            'imagen' => '1671853020.jpg',
        ),
        6=>array(
            'id' => '6',
            'fecha' => '2022-06-16',
            'categoria' => 'Bells',
            'titulo' => 'QUE LA EDUCACIÓN VIRTUAL NO TE DESCONECTE DESHUMANICE',
            'autor' => 'Coalición Trinacional',
            'pais' => 'Mexico',
            'imagen' => '1671853325.jpg',
        ),
        7=>array(
            'id' => '7',
            'fecha' => '2022-06-12',
            'categoria' => 'Solidarity',
            'titulo' => 'Dieron inicio las actividades en la Casa del Obrero Socialista Antonio Vital. COSAV',
            'autor' => 'Coalición Trinacional',
            'pais' => 'Mexico',
            'imagen' => '1671853676.jpg',
        ),
        8=>array(
            'id' => '8',
            'fecha' => '2022-03-02',
            'categoria' => 'Collaborations',
            'titulo' => 'Día Internacional de la Mujer 2022',
            'autor' => 'Coalición Trinacional',
            'pais' => 'Mexico',
            'imagen' => '1671853185.jpg',
        ),
        9=>array(
            'id' => '9',
            'fecha' => '2022-02-10',
            'categoria' => 'Solidarity',
            'titulo' => 'José Antonio Vital Galicia',
            'autor' => 'Coalición Trinacional',
            'pais' => 'Mexico',
            'imagen' => '1671853638.jpg',
        ),
        10=>array(
            'id' => '10',
            'fecha' => '2021-11-10',
            'categoria' => 'Actions',
            'titulo' => 'PRESENTACIÓN DE LIBRO EDUCACIÓN',
            'autor' => 'Coalición Trinacional',
            'pais' => 'Mexico',
            'imagen' => '1671853087.jpg',
        ),
)
?>