<?php
$articulo= array(
        1=>array(
            'id' => '1',
            'fecha' => '2022-11-09',
            'categoria' => 'Acciones',
            'titulo' => 'Huelga de maestros y maestras en Ontario, Canadá.',
            'autor' => 'Coalición Trinacional',
            'pais' => 'México',
            'contcorto' => 'Me complace brindarles una actualizaci&oacute;n sobre la situaci&oacute;n en Ontario, Canad&aacute;, con respecto a la protesta pol&iacute;tica de nuestros 55.000 compa&ntilde;eras y compa&ntilde;eros trabajadores de la educaci&oacute;n en el Sindicato Canadiense de Empleados P&uacute;blicos (CUPE).',
            'contlargo' => '<p style="text-align: justify;"><span>&nbsp; &nbsp; &nbsp;Me complace brindarles una actualizaci&oacute;n sobre la situaci&oacute;n en Ontario, Canad&aacute;, con respecto a la protesta pol&iacute;tica de nuestros 55.000 compa&ntilde;eras y compa&ntilde;eros trabajadores de la educaci&oacute;n en el Sindicato Canadiense de Empleados P&uacute;blicos (CUPE). Estos miembros de CUPE incluyen asistentes educativos, custodios, trabajadores con infantes y ni&ntilde;os, personal de oficina, t&eacute;cnicos, pat&oacute;logos del habla y lenguaje, </span><span><a tabindex="-1"></a></span><span>monitores de cafeter&iacute;a y muchos otros que conforman el equipo educativo.</span></p><p style="text-align: justify;"><span><img src="http://drive.google.com/uc?export=view&id=1DN_pnu6cIldo4SobYqfg0DjwkiPSEbl8" alt="luchas" width="100%" height="100%" caption="false" /></span></p><p style="text-align: justify;"><span>&nbsp; &nbsp;Como informamos la semana pasada, el gobierno aprob&oacute; una ley, conocida como &ldquo;Proyecto de Ley 28 - Ley para Mantener a los Estudiantes en Clase&rdquo;, que impuso unilateralmente un contrato a los miembros de CUPE, les quit&oacute; el derecho a la huelga e invoc&oacute; la cl&aacute;usula no obstante, un poder constitucional que permite que los gobierno anule partes de nuestra Carta de Derechos y Libertades por un per&iacute;odo de cinco a&ntilde;os. A pesar de esta medida, CUPE realiz&oacute; una protesta pol&iacute;tica el viernes y nuevamente el lunes. CUPE estaba en una posici&oacute;n de huelga LEGAL hasta que el gobierno aprob&oacute; la Ley.</span></p><p style="text-align: justify;"><span>&nbsp; &nbsp;Ayer por la ma&ntilde;ana, el Primer Ministro de Ontario, Doug Ford, y el Ministro de Educaci&oacute;n, Stephen Lecce, ofrecieron una conferencia de prensa. Anunciaron que DEROGAR&Iacute;AN el Proyecto de Ley 28 si CUPE acced&iacute;a a poner fin a su huelga y volver a la mesa de negociaci&oacute;n. El primer ministro enfrentaba una reacci&oacute;n fuerte del p&uacute;blico y los sindicatos de toda la provincia de Ontario y de todo Canad&aacute; hac&iacute;an una frente com&uacute;n para denunciar el proyecto de ley 28 y la llamada para una huelga general por parte de los sindicatos del sector p&uacute;blico y privado crec&iacute;a. CUPE obtuvo la promesa del primer ministro de Ontario de derogar el proyecto de ley 28 por escrito y m&aacute;s de 20 sindicatos del sector p&uacute;blico y privado se unieron en una conferencia de prensa m&aacute;s tarde en la ma&ntilde;ana para decir que regresar&iacute;an al trabajo y a la mesa de negociaciones.</span></p><p style="text-align: justify;"><span><img src="http://drive.google.com/uc?export=view&amp;id=1hFoehTERE4cVMtWN5g2Jn_DEnf9KCDSv" alt="luchas" width="100%" height="100%" caption="false" /></span></p><p style="text-align: justify;"><span>&nbsp; &nbsp; El intento de mano dura del gobierno de Ontario de forzar un contrato y eliminar el derecho a la huelga de los trabajadores de CUPE fracas&oacute;. &iexcl;Mostr&oacute; a todos los gobiernos de Canad&aacute; que cuando atacas a uno de nosotros, nos atacas a todos! Predomin&oacute; el poder de la solidaridad obrera. Sin embargo, nos sigue preocupando que un gobierno tome tal medida contra las y los trabajadores, especialmente los trabajadores de la educaci&oacute;n que se encuentran entre las personas peor pagadas que trabajan en el sistema educativo. OSSTF/FEESO representa a unos 21 000 trabajadores de la educaci&oacute;n, adem&aacute;s de m&aacute;s de 40 000 maestras y maestros en Ontario.</span></p><p style="text-align: justify;"><span>&nbsp; &nbsp; Nuestras negociaciones contin&uacute;an con el gobierno y nuestro sindicato no ha tomado un voto de huelga de los miembros todav&iacute;a. Ahora sabemos que todos los trabajadores nos respaldan, y agradezco a todos en la Coalici&oacute;n Trinacional por su apoyo y preparaci&oacute;n para actuar en nombre de nuestros compa&ntilde;eros de CUPE.</span></p>',
            'imagen' => '1668028457.jpg',
            'imagenbarner' => '1668028457.jpg',
        ),
        2=>array(
            'id' => '2',
            'fecha' => '2022-10-07',
            'categoria' => 'Conferencias',
            'titulo' => 'iniciamos los trabajos de la XV Conferencia  Trinacional en Defensa de la Educación, en Oaxaca, México.',
            'autor' => 'Coalición Trinacional',
            'pais' => 'México',
            'contcorto' => 'Programa de la XV Conferencia Trinacional en Defensa de la Educación Pública.',
            'contlargo' => '<p>        Programa de la XV Conferencia Trinacional en Defensa de la Educación Pública.        <br>        Les invitamos a seguir la transmisión en vivo a partir de las 4:30 pm (hora de México)        <br>        <a href="https://www.facebook.com/events/1192641061289271/?acontext=%7B%22ref%22%3A%2252%22%2C%22action_history%22%3A%22[%7B%5C%22surface%5C%22%3A%5C%22share_link%5C%22%2C%5C%22mechanism%5C%22%3A%5C%22share_link%5C%22%2C%5C%22extra_data%5C%22%3A%7B%5C%22invite_link_id%5C%22%3A807551150435135%7D%7D]%22%7D">            <<< Enlace de transmisión de Conferencia >>>        </a>    </p>    <img src="http://drive.google.com/uc?export=view&id=1qfy77fvLk621PMIC4Hpu9a7s5h6E_SVj" with=""            height="" class="img-fluid" alt="...">    <img src="http://drive.google.com/uc?export=view&id=1jSkPylhLMHQwxj74O3qUAhNNmfheFG_L" with=""            height="" class="img-fluid" alt="...">',
            'imagen' => '1665212453.jpg',
            'imagenbarner' => '1665212453.jpg',
        ),
        3=>array(
            'id' => '3',
            'fecha' => '2022-10-07',
            'categoria' => 'Conferencias',
            'titulo' => 'Compañeros de Canadá, Estados Unidos y México en la escuela Telesecundaria de San Juan Guelavía en Oaxaca, México.',
            'autor' => 'Coalición Trinacional',
            'pais' => 'México',
            'contcorto' => 'En la visita a las escuelas, nos recibieron las y los maestros y estudiantes, junto a los padres de familia y las comunidades.',
            'contlargo' => '<p class="text-primario">En la visita a las escuelas, nos recibieron las y los maestros y estudiantes, junto a los padres de familia y las comunidades.</p>
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <?php $img = ["1hpmDMEQSgq28yLHpi70sdn_A6iYWZX6Z",
    "1cwQL9JxSHJVQI1H_1Bp4-5VYU0gjh0dO",
    "1U5zD5SYI35a_W-J2xD0hxJuJ2aKSLZI2",
    "1e42F7wSJoT3SN7LnOBMkSURU438VO-GP",
    "1Uc461QV5qv2WuyOcfM-bNA-xcBmHoLb6",
    "1ZpCFAODcu5X1K_zil9TfBkcfX87nmtOR",
    "19Ggza6b0dio5jxX5E-cPPxUApuLLyXBs",
    "1uA0gCQOI1FwiDIjTwj08p0XOLLopew0d",
    "17otDcfbjtWjWKej2rys4g3U2PbfBh0ec",
    "13tNiEpI64IustFjvd0SKizGh7JG7ziC1",
    "1_M2u_SBdwc46F9Ckn6LDo-zaaVBUeIk5",
    "1MdE0UlNtVw_CwIW6_ivpjK52ok88U_II",
    "1xrQadLWlbAecIoGS_OkRpUa5D0OocxnG",
    "1z4NIMAIb3Gf7LlRiSKn44U6Xnt7IEdiL",
    "1prQmrm5XhDnGl4W5vpDhuJJiXAnovlyw"];   ?>

            <div class="carousel-item active text-center">
                <img src="http://drive.google.com/uc?export=view&id=<?php echo $img[0] ?>" width="720px" height="604px" class="img-fluid" alt="...">
            </div>
            <?php for ($i=1; $i < count($img); $i++) { ?>
            <div class="carousel-item  text-center">
                <img src="http://drive.google.com/uc?export=view&id=<?php echo $img[$i] ?>" width="720px" height="604px" class="img-fluid" alt="...">
            </div>
            <?php } ?>

        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>',
            'imagen' => '1665215300.jpg',
            'imagenbarner' => '1665215300.jpg',
        ),
        4=>array(
            'id' => '4',
            'fecha' => '2022-10-05',
            'categoria' => 'Conferencias',
            'titulo' => 'Conferencia de prensa presentación de la XV Conferencia Trinacional en Defensa de la Educación Pública',
            'autor' => 'Coalición Trinacional',
            'pais' => 'México',
            'contcorto' => 'A realizarse en Oaxaca los días 7, 8 y 9 de octubre.Donde participarán representantes de Canadá, Estados Unidos y México.En la conferencia estaremos analizando los problemas en común que tenemos los docentes y estudiantes y trazaremos una agenda común de lucha.',
            'contlargo' => '<div class="d-flex align-items-center">        <img src="http://drive.google.com/uc?export=view&id=1WtXtqsNi68oEVKtbNF2JtBK7c_-otc1D" with="150px"            height="150px" class="flex-shrink-0 me-3" alt="...">        <div class="text-center">            <p class="text-danger">Coalición Trinacional en Defensa de la Educación Pública</p>            <p class="text-danger">Trinational Coalition in Defense Public Education</p>            <p class="text-danger">- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -</p>        </div>    </div>    <div class="text-center">        <p class="text-danger fw-bold"><b> RUEDA DE PRENSA</b></p>        <p class="text-danger">Representaciones sindicales. De México, Estados Unidos y Canadá convocan a la XV            Conferencia Trinacional en Defensa de la Educación Pública con el fin de trazar una agenda de lucha para la            coyuntura.</p>    </div>    <br>    <p class="text-terciario">5 de octubre de 2022 <br> 13:00 horas</p>    <br>    <p class="text-primario">        <b></b>Lugar: Local del Sindicato Independiente de Trabajadores de la Universidad Autónoma Metropolitana        (SITUAM) ubicado en Calzada de Tlalpan Nº1036 Col. Nativitas Delegación Benito Juárez 03500 Ciudad de        México, a unas cuadras de metro Nativitas.</b>    </p>    <p class="text-primario">        &nbsp;Poco a poco comienza a estabilizarse la pandemia y en consecuencia se reabrieron las escuelas y        centros educativos de los diferentes niveles, no obstante, esta reapertura no contemplo el daño provocado        por la pandemia en la educación, ni garantiza que todos los niños y jóvenes regresen a la escuela. Asimismo,        muchos de los problemas que observamos hoy en el sector educativo son previos a la pandemia y continúan; la        vulnerabilidad a la que se enfrentan los niños, familias y comunidades de bajos ingresos, la desigual        cobertura en educación, la discriminación y exclusión por raza, clase y género, la precariedad salarial y de        condiciones de trabajo de los docentes, entre muchos otros aspectos que durante años hemos denunciado desde        la Coalición Trinacional en defensa de la educación pública.        <br>        &nbsp;A 30 años de nuestra fundación como Coalición Trinacional, representaciones sindicales,        trabajadores y trabajadoras de la educación, estudiantes y activistas comprometidas con la defensa del        derecho público a la educación de México, Estados Unidos y Canadá convocamos a los medios de comunicación        para presentar los trabajos y discusiones que se llevarán a cabo en la XV Conferencia Trinacional en Defensa        de la Educación Pública, a realizarse en Oaxaca, México los días 7,8 y 9 de octubre de 2022, con el fin de        trazar una agenda de lucha para la actual coyuntura.    </p>    <br>    <p class="text-terciario">        Mas información: seccionmexicana.coali@gmail.com   <br>     Dra. María de la Luz Arriaga 55 48 12 63 14</p>',
            'imagen' => '1665209716.jpg',
            'imagenbarner' => '1665209716.jpg',
        ),
        5=>array(
            'id' => '5',
            'fecha' => '2022-10-02',
            'categoria' => 'Acciones',
            'titulo' => '2 De Octubre No Se Olvida',
            'autor' => 'Coalición Trinacional',
            'pais' => 'México',
            'contcorto' => 'Hoy nos vemos en las calles, para juntas y juntos recordarle a la sociedad mexicana que la justicia contra los crímenes del Estado mexicano continúa ausente. ',
            'contlargo' => '<h3>2/Octubre/1968</h3><ul style="list-style-type: circle;"><li>Ni perd&oacute;n ni olvido.</li><li>Por los estudiantes que dieron voz a los sin voz.Por los que perdieron su vida.</li><li>Por los que defendieron sus ideales.</li><li>Por los que perdieron a un hijo, hermano amigo, etc.</li><li>Por la sangre derramada en la plaza de las tres culturas.</li><li>Por los encarcelados en Lecumberri.</li><li>Porque gracias a ellos hoy tenemos la educaci&oacute;n que tenemos.</li><li>Para que nunca muera su legado en el olvido.</li><li>Por eso y m&aacute;s...</li></ul><h3>&iexcl;Vivan los estudiantes!</h3>',
            'imagen' => '1664767597.jpg',
            'imagenbarner' => '1664763866.jpg',
        ),
        6=>array(
            'id' => '6',
            'fecha' => '2022-09-30',
            'categoria' => 'Conferencias',
            'titulo' => 'XVConferencia de la Coalición Trinacional en Defensa de la Educación Pública (México, Estados Unidos y Canadá).',
            'autor' => 'Coalición Trinacional',
            'pais' => 'México',
            'contcorto' => 'El tema que nos convoca en este momento de crisis y ante la necesidad de transformaciones profundas en nuestras sociedades es una educación pública para reconstruir la comunidad. ',
            'contlargo' => '<h2 style="text-align: center;"><strong><a href="https://www.facebook.com/hashtag/coalici%C3%B3ntrinacional?__eep__=6&amp;__cft__[0]=AZVG7AJBibsegUzQx4om9z4A3Z7rsFOf1FERCmLNSnzSYrwq-YCJ7-Idefbx7tqBsUjCiibU0x3b3QtDyP5ws23T0nW_6vpN-3FQB0MHd-kQy6Ox9e3Yhzx1udr_-sJBsSxsU424fPzmmYyPFUlWSjNtCraNisuwm7oIAv96D9bigA&amp;__tn__=*NK-R" target="_blank" rel="noopener"></a>XVConferencia de la Coalici&oacute;n Trinacional en Defensa de la Educaci&oacute;n P&uacute;blica (M&eacute;xico, Estados Unidos y Canad&aacute;).</strong> <br /><br /></h2><p style="text-align: justify;">&nbsp; &nbsp;Una vez m&aacute;s, como lo hemos venido realizando desde ya casi 30 a&ntilde;os, representaciones sindicales, trabajadores y trabajadoras, estudiantes y activistas comprometidas con la defensa del derecho p&uacute;blico a la educaci&oacute;n y con propuestas y reflexiones educativas, para la transformaci&oacute;n social, nos daremos cita los d&iacute;as 7,8 y 9 de octubre de 2022, en la ciudad de Oaxaca.</p><p style="text-align: justify;">&nbsp; &nbsp;El tema que nos convoca en este momento de crisis y ante la necesidad de transformaciones profundas en nuestras sociedades es &ldquo;una educaci&oacute;n p&uacute;blica para reconstruir la comunidad&rdquo;.<br /><br />&nbsp; &nbsp;Sabemos que las necesidades y problem&aacute;ticas en el terreno educativo son bastas y complejas y tenemos la certeza de que esfuerzo de reflexi&oacute;n colectiva y de elaboraci&oacute;n de la agenda de lucha y de definici&oacute;n de acciones solidarias, fortalecer&aacute; nuestro compromiso de lucha en la defensa de la educaci&oacute;n como derecho social, fundamental en la construcci&oacute;n de sociedades democr&aacute;ticas y con justicia social.</p><p style="text-align: justify;"><a href="https://www.facebook.com/hashtag/coalici%C3%B3ntrinacional" target="_blank" rel="noopener">#Coalici&oacute;nTrinacional</a><a href="https://www.facebook.com/hashtag/conferenciatrinacional" target="_blank" rel="noopener">#ConferenciaTrinacional</a></p>',
            'imagen' => '1664767623.jpg',
            'imagenbarner' => '1664762932.jpg',
        ),
        7=>array(
            'id' => '7',
            'fecha' => '2022-09-27',
            'categoria' => 'Campañas',
            'titulo' => 'A unos minutos de que comience la presentación del folleto *Entre transformaciones y continuidades en el derecho a la educación pública y gratuita en tiempos de la 4T*',
            'autor' => 'Coalición Trinacional',
            'pais' => 'México',
            'contcorto' => 'A unos minutos de que comience la presentación del folleto *Entre transformaciones y continuidades en el derecho a la educación pública y gratuita en tiempos de la 4T*',
            'contlargo' => '<p style="text-align: justify;"><em><span>&nbsp; &nbsp; A unos minutos de que comience la presentaci&oacute;n del folleto "<strong>Entre transformaciones y continuidades en el derecho a la educaci&oacute;n p&uacute;blica y gratuita en tiempos de la 4T"</strong></span></em></p><p style="text-align: justify;"><em>En la presentaci&oacute;n contaremos con la participaci&oacute;n de:</em></p><ul><li style="text-align: justify;"><span><strong>Mar&iacute;a de la Luz Blanca Arriaga Lemus</strong>. Coordinadora de la Secci&oacute;n Mexicana de la Coalici&oacute;n Trinacional en Defensa de la Educaci&oacute;n P&uacute;blica.</span></li><li style="text-align: justify;"><span><strong>Leticia Lopez Zamora</strong>. Secretaria General del Sindicato de la Uni&oacute;n de Trabajadores del Instituto de Educaci&oacute;n Media Superior - SUTIEMS.</span></li><li style="text-align: justify;"><span><strong>Ver&oacute;nica Teneria Mendieta</strong>. Grupo Tiempos Modernos.</span></li><li style="text-align: justify;"><span><strong>Mario Mendoza.</strong> Frente Estudiantil Independiente del Valle de M&eacute;xico.</span></li><li style="text-align: justify;"><span><strong>Modera: Natalia Castillo Mosso</strong>. Grupo Tiempos Modernos.</span><br /><br /><br /><br /><span class="fxk3tzhb b2rh1bv3 gh55jysx m8h3af8h ewco64xe kjdc1dyq ms56khn7 bq6c9xl4 eohcrkr5 akh3l2rg"><img height="16" width="16" alt="" referrerpolicy="origin-when-cross-origin" src="https://static.xx.fbcdn.net/images/emoji.php/v9/t6e/1/16/1f534.png" class="hoverZoom3 hoverZoomMouseover" /></span><span>&nbsp;Sigue la transmisi&oacute;n en vivo desde nuestra p&aacute;gina de Facebook</span></li></ul>',
            'imagen' => '1664302815.jpg',
            'imagenbarner' => '1664302815.jpg',
        ),
        8=>array(
            'id' => '8',
            'fecha' => '2022-09-10',
            'categoria' => 'Conferencias',
            'titulo' => 'Clausura de la Conferencia Nacional de la Sección Mexicana de la Coalición Trinacional en Defensa de la Educación Pública.',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'Tras una jornada ardua de discusión y exposición de planteamientos políticos en torno a la política educativa del gobierno actual y ante una Coyuntura tan complicada a nivel internacional, la sección mexicana de la Coalición cerro está tarde las propuestas y tareas que llevará a la XV Conferencia Trinacional en Defensa de la Educación Púbica, a realizarse en Oaxaca, México los días 7, 8 y 9 de octubre de 2022.',
            'contlargo' => '<p class="display-6">Hacia la XV Conferencia Trinacional (México, Estados Unidos, Canadá).</p><br>        <p class="lead">        &nbsp;&nbsp;Tras una jornada ardua de discusión y exposición de planteamientos políticos en torno a la política educativa del gobierno actual y ante una Coyuntura tan complicada a nivel internacional, la sección mexicana de la Coalición cerro está tarde las propuestas y tareas que llevará a la XV Conferencia Trinacional en Defensa de la Educación Púbica, a realizarse en Oaxaca, México los días 7, 8 y 9 de octubre de 2022.        <br><br>        <a href="conf-nacional.php"><span class="lead text-terciario">>>Enlace para ver todo el evento y su organización<<</span></a>        </p>',
            'imagen' => '1663791448.jpg',
            'imagenbarner' => '1663791448.jpg',
        ),
        9=>array(
            'id' => '9',
            'fecha' => '2022-09-01',
            'categoria' => 'Conferencias',
            'titulo' => 'Conferencia Nacional de la Sección Mexicana de la Coalición Trinacional en Defensa de la Educación Pública.',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'A las organizaciones sindicales, a los profesores, investigadores, estudiantes, activistas e interesados en defensa de la educación pública como un derecho social a participar en la Conferencia Nacional en Defensa de la Educación Pública 2022,se llevará a cabo del viernes 9 al sabado 10 de septiembre 2022',
            'contlargo' => '<p class="display-6">Hacia la XV Conferencia Trinacional (México, Estados Unidos, Canadá).</p><br>        <p class="lead">        &nbsp;&nbsp;Los sistemas educativos en el mundo han sufrido profundos estragos a consecuencia del cierre de escuelas y el confinamiento producto del COVID-19. Para muchos estudiantes no sólo representó una interrupción temporal en su educación sino un final abrupto para la misma, al incorporarse al trabajo, perder a sus padres o tutores o simplemente no tener las condiciones suficientes para ponerse al corriente en sus aprendizajes. Esta situación ha transgredido el tejido social y educativo afectando a la educación pública en el mundo, y la educación en México no ha sido la excepción.         <br><br>        &nbsp;&nbsp;Mientras tanto los trabajadores de la educación sufrieron transformaciones múltiples en sus condiciones de trabajo y; su práctica docente y profesional, mientras que el aprendizaje en línea exacerbó las desigualdades en educación. Nuestro gobierno no contaba con las políticas, la infraestructura ni los recursos necesarios para desarrollar el aprendizaje en línea de manera que se garantizara que todos los niños y las niñas, jóvenes y universitarios pudieran participar en igualdad de condiciones.          <br><br>        &nbsp;&nbsp;Poco a poco comienza a estabilizarse la pandemia y, en consecuencia, comienza la reapertura de las escuelas y centros educativos a diferentes niveles, no obstante, esta reapertura no deshará el daño provocado en la educación, ni garantizará que todos los niños y jóvenes regresen a la escuela. Puesto que, muchos problemas que observamos hoy en el sector educativo son preexistentes a ella; la vulnerabilidad a la que se enfrentan los niños, familias y comunidades de bajos ingresos, la desigual cobertura en educación, la discriminación y exclusión por raza, clase y género, la precariedad salarial y de condiciones de trabajo de los docentes, entre muchos otros aspectos que durante años hemos denunciado desde la Coalición Trinacional en Defensa de la Educación Pública.        &nbsp;&nbsp;Ante este panorama consideramos necesaria una reflexión que nos permita identificar cuáles son los estragos que la pandemia ha ocasionado en la educación pública en México, así como identificar las acciones indispensables para superar los problemas provocados por ella e identificar las alternativas para reconstruir a las comunidades educativas que han sido afectadas por el distanciamiento social y el auto-centramiento provocado por el confinamiento; al mismo tiempo, necesitamos recuperar las demandas en defensa de la educación pública que apuntan a exigir al gobierno mexicano el cumplimiento de sus responsabilidades como garante del derecho a la educación; por ello:           <br><br>        </p>        <p class="display-6"><b>Convocamos.</b></p><br>        <p class="lead">        &nbsp;&nbsp;A las organizaciones sindicales, a los profesores, investigadores, estudiantes, activistas e interesados en',
            'imagen' => '1663800748.png',
            'imagenbarner' => '1663800748.png',
        ),
        10=>array(
            'id' => '10',
            'fecha' => '2022-08-05',
            'categoria' => 'Conferencias',
            'titulo' => 'XV Conferencia Trinacional en Defensa de la Educación Pública',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'Próxima a celebrarse en el estado de Oaxaca durante los días 7, 8 y 9 de octubre de 2022, la quinceava edición de la Conferencia Trinacional en Defensa de la Educación Pública',
            'contlargo' => '<p class="text-muted lead">México / Estados Unidos / Canadá</p>        <br>        <p class="lead">        &nbsp;&nbsp;Próxima a celebrarse en el estado de Oaxaca durante los días 7, 8 y 9 de octubre de 2022, la quinceava edición de la Conferencia Trinacional en Defensa de la Educación Pública, tendrá lugar ante las múltiples preocupaciones que docentes, sindicalistas, investigadores, estudiantes y activistas dentro del sector educativo comparten. Dicho espacio dará lugar a la reflexión y dialogo, tanto de las problemáticas que se vienen profundizando desde antes de la pandemia, como aquellos que se derivan de las dinámicas sociales que la pandemia y su administración de parte de los Estados impusieron a las comunidades educativas.        <br><br>        &nbsp;&nbsp;Contexto bajo el cual diversas personalidades, organizaciones y comunidades educativas en Norteamérica estaremos compartiendo y deliberando las propuestas necesarias para recuperar o profundizar procesos comunitarios, que hoy son fundamentales para enfrentar el contexto que enfrente la educación pública como derecho social y humano.        <br><br>        &nbsp;&nbsp;En breve daremos a conocer la convocatoria y la información correspondiente para que quienes tengan interés puedan participar y acceder a las discusiones, reflexiones y propuestas producto de esta quinceava conferencia.        <br>        </p>',
            'imagen' => '1663801115.jpg',
            'imagenbarner' => '1663801115.jpg',
        ),
        11=>array(
            'id' => '11',
            'fecha' => '2022-08-05',
            'categoria' => 'Foros',
            'titulo' => 'Foro Regreso a clases presenciales en el ciclo escolar 2023-1',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'Sabemos que es una necesidad pedagógica y de salud mental, reencontrarnos en las aulas y los auditorios, para desarrollar los procesos de enseñanza - aprendizaje, de investigación, de difusión, de extensión',
            'contlargo' => '<p class="text-terciario lead">Las académicas y los académicos de la UNAM</p><br>        <p class="lead">        &nbsp;&nbsp;Como acostumbran las autoridades universitarias, sin consulta alguna, han ordenado el regreso a clases presenciales en todos los niveles educativos y en todos los planteles universitarios.        <br><br>        &nbsp;&nbsp;Las académicas y los académicos de la UNAM, sabemos que es una necesidad pedagógica y de salud mental, reencontrarnos en las aulas y los auditorios, para desarrollar los procesos de enseñanza - aprendizaje, de investigación, de difusión, de extensión.         <br><br>        &nbsp;&nbsp;Sin embargo, muchas y muchos consideramos que es indispensable realizar un ejercicio de evaluación de lo que hemos vivido en la docencia durante la pandemia. Valorar la educación a través de plataformas, sus impactos en la enseñanza, en la intensificación y el alargamiento de nuestras jornadas laborales, así como las afectaciones de las condiciones de estudio de las y los jóvenes.        <br><br>        &nbsp;&nbsp;La Universidad tiene la obligación, de que los expertos de salud pública con que contamos hablen con las comunidades y nos expliquen la situación actual del COVID, en todas y cada una de las escuelas.</p>',
            'imagen' => '1663801338.jpg',
            'imagenbarner' => '1663801338.jpg',
        ),
        12=>array(
            'id' => '12',
            'fecha' => '2022-07-05',
            'categoria' => 'Campañas',
            'titulo' => 'Coalición Trinacional en Defensa de la Educación da a conocer folleto en la ANR de la CNTE',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'folleto "Entre transformaciones y continuidades en el derecho a la educación pública en tiempos de la #4T"',
            'contlargo' => '<p class="text-terciario lead">"Entre transformaciones y continuidades en el derecho a la educación pública en tiempos de la #4T"</p><br>        <p class="lead">        &nbsp;&nbsp;Una comisión de la sección mexicana de la Coalición Trinacional en Defensa de la Educación Pública se hizo presente durante la Asamblea Nacional Representativa de la CNTE, para dar un saludo a los trabajos y compartir el folleto "Entre transformaciones y continuidades en el derecho a la educación pública en tiempos de la #4T".En donde se han recopilado diversos materiales de reflexión y balance político sobre las diversas problemáticas presentes en el sector educativo.        <br><br>        &nbsp;&nbsp;Compartimos la invitación a asistir el próximo martes 13 de septiembre en la Facultad de Ciencias Políticas y Sociales - #FCPyS de la #UNAM, a la presentación del más reciente material de discusión y debate sobre la política educativa y el derecho a la #educación en el marco del gobierno actual.Este folleto es un esfuerzo por compilar materiales escritos por compañeras y compañeros que integran la Sección Mexicana de la Coalición Trinacional en Defensa de la Educación Pública.        <br><br>         Podrás adquirir el folleto durante la presentación o bien se puede descargar escaneando el código QR en el cartel.</p>',
            'imagen' => '1663801235.jpg',
            'imagenbarner' => '1663801235.jpg',
        ),
        13=>array(
            'id' => '13',
            'fecha' => '2022-06-16',
            'categoria' => 'Acciones',
            'titulo' => 'Solidaridad con la huelga del SUTIEMS',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'Compartimos la carta de Solidaridad con la huelga del SUTIEMS, que enviamos al periódico La Jornada para su publicación.',
            'contlargo' => '<p class="lead">La Coalición Trinacional Respalda al Sutiems        <br>        &nbsp;&nbsp;Reconocemos la importancia que el gobierno de la capital otorga al modelo del Instituto de Educación Media Superior de la Ciudad de México (IEMS), al inaugurar en los últimos meses nuevos planteles y ampliar la matrícula para un sector de los jóvenes que requieren de mayor atención debido a sus condiciones socioeconómicas.        <br><br>        &nbsp;&nbsp;Lamentamos que a esa ampliación no corresponda un presupuesto para el funcionamiento y mejoramiento del enseñanza-aprendizaje. Sabemos del compromiso para establecer mejores condiciones de trabajo docente y administrativo en las instituciones educativas de la ciudad, particularmente las que dependen de su gestión y asignación presupuestal, en contraste a lo que sucede en otros sistemas de educación media superior, incluyendo los de la UNAM, donde prevalece el pago por hora pizarrón, eventualidad del empleo, largas jornadas laborales y salarios indignos.        <br><br>        &nbsp;&nbsp;Confiamos en la voluntad política de Claudia Sheinbaum para resolver las demandas, concretar el compromiso presidencial de aumento salarial por encima de la inflación e impulsar el modelo alternativo del IEMS, conquista de la izquierda en nuestro país.        Nuestra solidaridad con la lucha del Sutiems, nos adherimos a su consigna "Por educación y trabajo dignos".        <br><br>        &nbsp;&nbsp;María de la Luz Arriaga</p>',
            'imagen' => '1663800940.jpg',
            'imagenbarner' => '1663800941.jpg',
        ),
        14=>array(
            'id' => '14',
            'fecha' => '2022-06-16',
            'categoria' => 'Campañas',
            'titulo' => 'Que la Educación virtual no te Desconecte Deshumanice',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'El 5 de octubre fue instituido por la UNESCO como el día mundial de los docentes,para reconocer la labor de maestras y maestros.',
            'contlargo' => '<p class="lead">RECONOCIMIENTO A LABOR DOCENTE        <br>        &nbsp;&nbsp;El 5 de octubre fue instituido por la UNESCO como el día mundial de los docentes, para reconocer la labor de maestras y maestros. En el momento crítico para la educación y la profesión de maestros y maestras que vivimos por la masificación de la educación virtualizada que han impuesto los gobiernos en el mundo, nos unimos a las voces de millones de docentes- de educación básica, media superior y superior- que reclamamos condiciones dignas de trabajo y el respeto a nuestro derecho a ser considerados en las decisiones de política educativa que adopten las autoridades.        <br><br>        &nbsp;&nbsp; En el marco de esta celebración, acudiremos el jueves 8 de octubre a las 12hs a Palacio Nacional a reiterar nuestras demandas de apertura de foros de discusión sobre la educación que necesitamos en la nueva realidad.        <br><br>        &nbsp;&nbsp; Que la SEP, dé a conocer el programa estratégico de mejora de infraestructura y garantía sanitaria de las instalaciones escolares para el regreso presencial a clases cuando así lo permitan las autoridades de Salud.        Acceso universal y gratuito a internet, como un bien público.        <br><br>        &nbsp;&nbsp; Condiciones de trabajo dignos, solicitamos se detenga el proceso de precarización laboral puesto en marcha y la sobresaturación de grupos en todos los niveles educativos, particularmente, el problema se agudiza en educación media superior, donde la mayoría de los profesores son pagados a destajo, por hora pizarrón impartida, atienden hasta 14 grupos, con más de 50 alumnos por actividad académica y con contratos interinos, retraso en sus pagos y un pobre apoyo para enfrentar clases a distancia o en línea.        <br><br>        &nbsp;&nbsp; Sección Mexicana de la Coalición Trinacional en Defensa de la Educación Pública.        <br><br></p>        <h5><b>María de la Luz Arriaga</b></h5>',
            'imagen' => '1663801693.jpg',
            'imagenbarner' => '1663801693.jpg',
        ),
        15=>array(
            'id' => '15',
            'fecha' => '2022-06-12',
            'categoria' => 'Solidaridad',
            'titulo' => 'Dieron inicio las actividades en la Casa del Obrero Socialista Antonio Vital. COSAV',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'El 10 de junio, realizamos el Foro Qué pasa en el sector Salud, en la casa ubicada en Antonio García Cubas 122 A en la Colonia obrera, que albergará , provisionalmente a la COSAV.',
            'contlargo' => '<p class="text-terciario lead">Contribuir a la formación y apoyo para la organización democrática e independiente de las trabajadoras y los trabajadores mexicanos</p>        <p class="lead">        &nbsp;&nbsp; Dieron inicio las actividades en la Casa del Obrero Socialista Antonio Vital. COSAV        El 10 de junio, realizamos el Foro Qué pasa en el sector Salud, en la casa ubicada en Antonio García Cubas 122 A en la Colonia obrera, que albergará , provisionalmente a la COSAV.        <br><br>        &nbsp;&nbsp;En los próximos días, daremos a conocer el programa de actividades para el semestre en curso y los invitamos a conocer el proyecto, accediendo al Facebook de la Alianza de trabajadores de la Salud y empleados públicos, al de la Coalición Trinacional en defensa de la educación, Sección Mexicana y al de José Antonio Vital Galicia, que aún está vigente.        <br><br>        &nbsp;&nbsp;También , si fuera de su interés , los invitamos a formar parte del Comité fundador de la Casa del Obrero Socialista Antonio Vital, como un espacio de apoyo, asesoría, educación, comunicación y cultura, Un centro de información , análisis y sistematización de experiencias y elaboración de propuestas, de recuperación de la memoria histórica de las luchas, para contribuir a la formación y apoyo para la organización democrática e independiente de las trabajadoras y los trabajadores mexicanos.        <br><br>        El correo electrónico es: <b> saludyrevolucion1818@gmail.com</b><br>        Teléfono: <b>55 5676 1789</b>        </p>',
            'imagen' => '1663801038.jpg',
            'imagenbarner' => '1663801038.jpg',
        ),
        16=>array(
            'id' => '16',
            'fecha' => '2022-03-02',
            'categoria' => 'Colaboraciones',
            'titulo' => 'Día Internacional de la Mujer 2022',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'Igualdad de género hoy para un mañana sostenible',
            'contlargo' => '<p class="lead">        &nbsp;&nbsp; El tema del Día Internacional de la Mujer de hoy 8 de marzo de 2022, Igualdad de género hoy para un mañana sostenible, reconoce la contribución de las mujeres y las niñas de todo el mundo, que están liderando los esfuerzos de respuesta, mitigación y adaptación al cambio climático para construir un futuro más sostenible para todas las personas.        <br><br>        &nbsp;&nbsp;Potenciar la igualdad de género en el contexto de la crisis climática y la reducción del riesgo de desastres es uno de los mayores desafíos mundiales del siglo XXI. Los aspectos relacionados con el cambio climático y la sostenibilidad han tenido y seguirán teniendo consecuencias graves y duraderas en nuestro desarrollo social, económico y medioambiental.        <br><br>        &nbsp;&nbsp;Las personas más vulnerables y marginadas son quienes sufren sus efectos más nefastos. Cada vez es más evidente que las mujeres son más vulnerables al impacto del cambio climático que los hombres, ya que constituyen la mayoría de la población pobre del mundo y son más dependientes de los recursos naturales que están bajo la amenaza del cambio climático.        <br><br>        &nbsp;&nbsp;En el 2021, en el Foro Generación Igualdad, se puso en marcha la Coalición para la Acción sobre la acción feminista por la justicia climática, que reúne a Gobiernos, a empresas del sector privado, al sistema de las Naciones Unidas y a la sociedad civil con el fin de adoptar compromisos concretos para justicia climática. Este Día Internacional de la Mujer, la Coalición para la Acción está impulsando la inversión y la acción global centradas en financiar soluciones climáticas con justicia de género, aumentar el liderazgo de las mujeres en la economía verde, mejorar la resiliencia de las mujeres y las niñas a los desastres y los impactos climáticos e incrementar el uso de los datos sobre igualdad de género y clima.        <br><br>        <h5>Cronología de la conmemoración</h5>        <br><br>        &nbsp;&nbsp;La primera conmemoración se realizó el 19 de marzo de 1911 en Europa: Alemania, Austria, Dinamarca y Suiza; desde entonces se ha extendido a otros países y continentes.        <br><br>        &nbsp;&nbsp;Después de la revolución de 1917 ocurrida en la Unión Soviética, en 1922 la dirigente bolchevique Alexandra Kollontai (que desde su nombramiento como comisaria del Pueblo para la Asistencia Pública logró el voto para la mujer) consiguió que el 8 de marzo se considerase fiesta oficial en la Unión Soviética, aunque laborable. El 8 de mayo de 1965 por decreto del Sóviet Supremo de la Unión Soviética se declaró no laborable el Día Internacional de la Mujer.        <br><br>        &nbsp;&nbsp;Desde su aprobación oficial por la Unión Soviética la fiesta comenzó a celebrarse en otros muchos países. En China se celebra desde 1922. En España se celebró por primera vez en 1936.        <br><br>        &nbsp;&nbsp;En 1975, la ONU celebró el Año Internacional de la Mujer. En di',
            'imagen' => '1663801463.jpg',
            'imagenbarner' => '1663801463.jpg',
        ),
        17=>array(
            'id' => '17',
            'fecha' => '2022-02-10',
            'categoria' => 'Solidaridad',
            'titulo' => 'José Antonio Vital Galicia',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'Falleció el luchador social José Antonio Vital Galicia, en la CDMX',
            'contlargo' => '<p class="lead">        &nbsp;&nbsp; Ciudad de México. José Antonio Vital Galicia, luchador social desde hace más de cuatro décadas, falleció este sábado a los 63 años de edad en la Ciudad de México, víctima de cáncer biliar.        <br><br>        &nbsp;&nbsp;El deceso fue confirmado por la Alianza de Trabajadores de la Salud y Empleados Públicos, organización que coordinó y desde donde encabezó una lucha incansable por la seguridad social, los derechos de los trabajadores y la democracia sindical.&nbsp;&nbsp;&nbsp;&nbsp;Ciudad de México. José Antonio Vital Galicia, luchador social desde hace más de cuatro décadas, falleció este sábado a los 63 años de edad en la Ciudad de México, víctima de cáncer biliar.<br><br>        &nbsp;&nbsp;El deceso fue confirmado por la Alianza de Trabajadores de la Salud y Empleados Públicos, organización que coordinó y desde donde encabezó una lucha incansable por la seguridad social, los derechos de los trabajadores y la democracia sindical.        <br><br>        &nbsp;&nbsp;Desde la primera semana de diciembre de 2021, Antonio Vital permaneció internado en el hospital 20 de Noviembre del Instituto de Seguridad y Servicios Sociales para los Trabajadores del Estado (Issste) por un tumor en vías biliares, enfermedad detectada en agosto de ese año a partir de estudios médicos que él realizó por cuenta propia.        <br><br>        &nbsp;&nbsp;La basificación de 86 mil empleados del sector salud; la restructuración de créditos hipotecarios Fovissste que se volvieron impagables y el fortalecimiento de los servicios médicos y de seguridad social, fueron algunas de las demandas que Antonio Vital planteó desde la Alianza.        <br><br>        &nbsp;&nbsp;Asimismo, ha respaldado las luchas contra la privatización de los servicios médicos y solicitó la intervención de la Secretaría de la Función Pública para investigar el uso de los rendimientos del fondo de vivienda del Issste que asciende a 22 mil millones de pesos.        <br><br>        &nbsp;&nbsp;Antonio Vital fue dirigente sindical de la sección 14 del Sindicato Nacional de Trabajadores de la Secretaría de Salud (SNTSA). En 1976 participó en la lucha por igualar y homologar salarios y condiciones laborales de todo el personal del sector salud, lo cual logró en el año de 1985.        <br><br>        &nbsp;&nbsp;En 1978, durante la huelga realizada por más de 5 mil trabajadores en el Hospital General de México, Antonio Vital fue encarcelado y desde entonces mantuvo la lucha por el derecho a la salud y la vida.        <br><br>        &nbsp;&nbsp;Sus familiares y amigos dan el último adiós al luchador social en los velatorios del Issste, de la avenida San Fernando, en Tlalpan.</p>',
            'imagen' => '1663801794.jpg',
            'imagenbarner' => '1663801794.jpg',
        ),
        18=>array(
            'id' => '18',
            'fecha' => '2021-11-10',
            'categoria' => 'Acciones',
            'titulo' => 'Presentación de Libro Educación',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'La Coalición Trinacional en Defensa de la educación pública y el SUTIEMS invitan este sábado 13 de noviembre a la presentación del libro: Educación Pública, Neo-liberalismo y Profesores.',
            'contlargo' => '<p class="lead">        &nbsp;&nbsp;La Coalición Trinacional en Defensa de la educación pública y el SUTIEMS invitan este sábado 13 de noviembre a la presentación del libro: Educación Pública, Neoliberalismo y Profesores.         <br><br>        &nbsp;&nbsp;Contaremos con la presencia del autor, quien es dirigente sindical de las y los trabajadores de la Educación en Ontario, Canadá.         <br><br>        &nbsp;&nbsp;La transmisión se llevará a cabo a través de la página de Facebook de la Coalición Trinacional y el canal de YouTube del SUTIEMS. Los esperamos.        <br><br>        &nbsp;&nbsp;El presente trabajo pretende aportar al análisis de la convicción social de que no existe relación entre neoliberalismo y globalización por un lado, y la tarea cotidiana de educar por otro, ya que en el interior de la misma conviven convicciones que remiten a las concepciones mismas de neoliberalismo, globalización, educación y Pedagogía. Éstas tienen un fondo de verdad parcial, gracias al trabajo que la ideología dominante1 realiza día a día, con la invalorable ayuda de los medios masivos de comunicación. Que sean verdades parciales ayuda a transformarlas en grandes desaciertos y obstáculos para comprender y transformar el mundo depredador en el que mal viven millones de personas en el mundo.        <br><br>        &nbsp;&nbsp;La tesis de la cual se parte es que el neoliberalismo, la globalización y la educación, son prácticas sociales que conforman una totalidad socio-político-económica y cultural no exenta de contradicciones. Estas últimas alientan y promueven tanto su legitimación como su superación. En otro orden, se considera probable que dicha superación cumpla su proceso en prácticas educativas en sentido amplio, y no tanto en el sentido restringido de educación al interior de las instituciones educativas. Esto parece obvio por ser las instituciones educativas la concreción de proyectos político-pedagógicos más direccionados que las prácticas educativas no formales que atraviesan la vida cotidiana. Lo planteado no es obstáculo para realizar el análisis hacia el interior de las instituciones educativas. Por el contrario, este ámbito exige ser estudiado, en el entendido de que siempre existe algún nivel de prácticas contra-hegemónicas de las que es necesario tomar conciencia para fortalecerlas en aras de la transformación, perspectiva pedagógica que convive con otras, más o menos conflictivamente. Puede entenderse a la Pedagogía como una pluralidad discursiva que da cuenta de estos fenómenos de diferentes maneras: al tiempo que se instala como discurso legitimador de lo existente y lo investiga descriptiva e incluso interpretativamente, construye una presencia crítica con prácticas de investigación también interpretativas pero con un propósito transformador, aunque éstas sean, a nuestro criterio, más escasas.        <br><br>        &nbsp;&nbsp;Interesa trabajar el tema particularmente con respecto a la formación docente tradicionalmente organizada p',
            'imagen' => '1663801583.jpg',
            'imagenbarner' => '1663801583.jpg',
        ),
        19=>array(
            'id' => '16',
            'fecha' => '2022-03-02',
            'categoria' => 'Colaboraciones',
            'titulo' => 'Día Internacional de la Mujer 2022',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'Igualdad de género hoy para un mañana sostenible',
            'contlargo' => '<p class="lead">        &nbsp;&nbsp; El tema del Día Internacional de la Mujer de hoy 8 de marzo de 2022, Igualdad de género hoy para un mañana sostenible, reconoce la contribución de las mujeres y las niñas de todo el mundo, que están liderando los esfuerzos de respuesta, mitigación y adaptación al cambio climático para construir un futuro más sostenible para todas las personas.        <br><br>        &nbsp;&nbsp;Potenciar la igualdad de género en el contexto de la crisis climática y la reducción del riesgo de desastres es uno de los mayores desafíos mundiales del siglo XXI. Los aspectos relacionados con el cambio climático y la sostenibilidad han tenido y seguirán teniendo consecuencias graves y duraderas en nuestro desarrollo social, económico y medioambiental.        <br><br>        &nbsp;&nbsp;Las personas más vulnerables y marginadas son quienes sufren sus efectos más nefastos. Cada vez es más evidente que las mujeres son más vulnerables al impacto del cambio climático que los hombres, ya que constituyen la mayoría de la población pobre del mundo y son más dependientes de los recursos naturales que están bajo la amenaza del cambio climático.        <br><br>        &nbsp;&nbsp;En el 2021, en el Foro Generación Igualdad, se puso en marcha la Coalición para la Acción sobre la acción feminista por la justicia climática, que reúne a Gobiernos, a empresas del sector privado, al sistema de las Naciones Unidas y a la sociedad civil con el fin de adoptar compromisos concretos para justicia climática. Este Día Internacional de la Mujer, la Coalición para la Acción está impulsando la inversión y la acción global centradas en financiar soluciones climáticas con justicia de género, aumentar el liderazgo de las mujeres en la economía verde, mejorar la resiliencia de las mujeres y las niñas a los desastres y los impactos climáticos e incrementar el uso de los datos sobre igualdad de género y clima.        <br><br>        <h5>Cronología de la conmemoración</h5>        <br><br>        &nbsp;&nbsp;La primera conmemoración se realizó el 19 de marzo de 1911 en Europa: Alemania, Austria, Dinamarca y Suiza; desde entonces se ha extendido a otros países y continentes.        <br><br>        &nbsp;&nbsp;Después de la revolución de 1917 ocurrida en la Unión Soviética, en 1922 la dirigente bolchevique Alexandra Kollontai (que desde su nombramiento como comisaria del Pueblo para la Asistencia Pública logró el voto para la mujer) consiguió que el 8 de marzo se considerase fiesta oficial en la Unión Soviética, aunque laborable. El 8 de mayo de 1965 por decreto del Sóviet Supremo de la Unión Soviética se declaró no laborable el Día Internacional de la Mujer.        <br><br>        &nbsp;&nbsp;Desde su aprobación oficial por la Unión Soviética la fiesta comenzó a celebrarse en otros muchos países. En China se celebra desde 1922. En España se celebró por primera vez en 1936.        <br><br>        &nbsp;&nbsp;En 1975, la ONU celebró el Año Internacional de la Mujer. En di',
            'imagen' => '1663801463.jpg',
            'imagenbarner' => '1663801463.jpg',
        ),
        20=>array(
            'id' => '16',
            'fecha' => '2022-03-02',
            'categoria' => 'Colaboraciones',
            'titulo' => 'Día Internacional de la Mujer 2022',
            'autor' => 'Coalición trinacional',
            'pais' => 'México',
            'contcorto' => 'Igualdad de género hoy para un mañana sostenible',
            'contlargo' => '<p class="lead">        &nbsp;&nbsp; El tema del Día Internacional de la Mujer de hoy 8 de marzo de 2022, Igualdad de género hoy para un mañana sostenible, reconoce la contribución de las mujeres y las niñas de todo el mundo, que están liderando los esfuerzos de respuesta, mitigación y adaptación al cambio climático para construir un futuro más sostenible para todas las personas.        <br><br>        &nbsp;&nbsp;Potenciar la igualdad de género en el contexto de la crisis climática y la reducción del riesgo de desastres es uno de los mayores desafíos mundiales del siglo XXI. Los aspectos relacionados con el cambio climático y la sostenibilidad han tenido y seguirán teniendo consecuencias graves y duraderas en nuestro desarrollo social, económico y medioambiental.        <br><br>        &nbsp;&nbsp;Las personas más vulnerables y marginadas son quienes sufren sus efectos más nefastos. Cada vez es más evidente que las mujeres son más vulnerables al impacto del cambio climático que los hombres, ya que constituyen la mayoría de la población pobre del mundo y son más dependientes de los recursos naturales que están bajo la amenaza del cambio climático.        <br><br>        &nbsp;&nbsp;En el 2021, en el Foro Generación Igualdad, se puso en marcha la Coalición para la Acción sobre la acción feminista por la justicia climática, que reúne a Gobiernos, a empresas del sector privado, al sistema de las Naciones Unidas y a la sociedad civil con el fin de adoptar compromisos concretos para justicia climática. Este Día Internacional de la Mujer, la Coalición para la Acción está impulsando la inversión y la acción global centradas en financiar soluciones climáticas con justicia de género, aumentar el liderazgo de las mujeres en la economía verde, mejorar la resiliencia de las mujeres y las niñas a los desastres y los impactos climáticos e incrementar el uso de los datos sobre igualdad de género y clima.        <br><br>        <h5>Cronología de la conmemoración</h5>        <br><br>        &nbsp;&nbsp;La primera conmemoración se realizó el 19 de marzo de 1911 en Europa: Alemania, Austria, Dinamarca y Suiza; desde entonces se ha extendido a otros países y continentes.        <br><br>        &nbsp;&nbsp;Después de la revolución de 1917 ocurrida en la Unión Soviética, en 1922 la dirigente bolchevique Alexandra Kollontai (que desde su nombramiento como comisaria del Pueblo para la Asistencia Pública logró el voto para la mujer) consiguió que el 8 de marzo se considerase fiesta oficial en la Unión Soviética, aunque laborable. El 8 de mayo de 1965 por decreto del Sóviet Supremo de la Unión Soviética se declaró no laborable el Día Internacional de la Mujer.        <br><br>        &nbsp;&nbsp;Desde su aprobación oficial por la Unión Soviética la fiesta comenzó a celebrarse en otros muchos países. En China se celebra desde 1922. En España se celebró por primera vez en 1936.        <br><br>        &nbsp;&nbsp;En 1975, la ONU celebró el Año Internacional de la Mujer. En di',
            'imagen' => '1663801463.jpg',
            'imagenbarner' => '1663801463.jpg',
        )
)
?>