<?php
$organiza= array(
        1=>array(
            "fecha" => "2022-09-01",
            "imagen" => "1662079359.png",
            "tipo" => "Sindicato, Sección Mexicana",
            "titulo" => "SUTIEMS Sindicato de la Unión de los Trabajadores",
            "direc" => "Concepción Beistegui 1810 d. colonia Narvarte oriente, alcaldía Benito Juárez, CDMX c.p. 03020",
            "url" => "INFO@SUTIEMS.ORG",
            "fone" => "55 8464 1577",
        ),
        2=>array(
            "fecha" => "2022-09-01",
            "imagen" => "1662082942.png",
            "tipo" => "Sindicato, Sección Canada",
            "titulo" => "OSSTF/OFEESO Ontario Secondary School Teachers Federation",
            "direc" => "49 Mobile Drive Toronto, ON M4A 1H5",
            "url" => "https://www.osstf.on.ca/en-CA",
            "fone" => "416-751-8300",
        ),
        3=>array(
            "fecha" => "2022-09-01",
            "imagen" => "1662080190.png",
            "tipo" => "Sindicato, Sección Mexicana",
            "titulo" => "CETEG Coordinadora Estatal de los Trabajadores de la Educación en Guerrero",
            "direc" => "*****",
            "url" => "http://ceteg.blogspot.com/",
            "fone" => "",
        ),
        4=>array(
            "fecha" => "2022-09-01",
            "imagen" => "1662080461.png",
            "tipo" => "Sección, Seccion Mexicana",
            "titulo" => "Sección XXII, Oaxaca",
            "direc" => "Armenta y López #221, Centro Oaxaca de Juarez, Oaxaca",
            "url" => "https://www.cencos22oaxaca.org/",
            "fone" => "951 475 3348",
        ),
        5=>array(
            "fecha" => "2022-09-01",
            "imagen" => "1662081002.png",
            "tipo" => "Sindicato, Sección Mexicana",
            "titulo" => "MMPV Movimiento Magisterial Popular Veracruzano",
            "direc" => "*****",
            "url" => "https://www.facebook.com/MMPVOFICIAL",
            "fone" => "",
        ),
        6=>array(
            "fecha" => "2022-09-01",
            "imagen" => "1662082425.png",
            "tipo" => "Sindicato, Seccion Canada",
            "titulo" => "BCTF Federación de Maestros de la Columbia Británica",
            "direc" => "100 - 550 West 6th Avenue Vancouver, Columbia Británica, Canadá V5Z 4P2",
            "url" => "https://www.bctf.ca/",
            "fone" => "604-871-2283",
        ),
        7=>array(
            "fecha" => "2022-09-01",
            "imagen" => "1662083133.png",
            "tipo" => "Sindicato, Seccion Estados Unidos",
            "titulo" => "UTLA United Teachers Los Angeles",
            "direc" => "3303 Wilshire Blvd., 10th Floor, Los Ángeles, CA 90010",
            "url" => "www.utla.net",
            "fone" => "213) 487-5560, (800) 556-8852",
        ),
        8=>array(
            "fecha" => "2022-09-01",
            "imagen" => "1662083269.png",
            "tipo" => "Sindicato",
            "titulo" => "CTU Sindicato de Maestros de Chicago",
            "direc" => "Chicago, IL 60612",
            "url" => "",
            "fone" => "",
        ),
        9=>array(
            "fecha" => "2022-09-01",
            "imagen" => "1662083354.png",
            "tipo" => "Sindicato, Seccion Estados Unidos",
            "titulo" => "Colegio los ríos federación de maestros.",
            "direc" => "2126 K Street Sacramento, CA 95816",
            "url" => "https://www.lrcft.org/",
            "fone" => "916-448-2452",
        ),
        10=>array(
            "fecha" => "2022-09-01",
            "imagen" => "1662083471.png",
            "tipo" => "Plataforma de organizaciones, Organización fratern",
            "titulo" => "Red Social para la Educación Pública en las Américas",
            "direc" => "Vancouver, Columbia Británica, Canadá V5K 1Z8",
            "url" => "idea-network.ca",
            "fone" => "604-708-1495",
        ),
        11=>array(
            "fecha" => "2022-09-01",
            "imagen" => "1662083562.png",
            "tipo" => "Organización político- social, Organización frater",
            "titulo" => "Alianza de trabajadores de la salud y empleados públicos",
            "direc" => "Antonio García Cubas 122A, Obrera, Cuauhtémoc, 06800 Ciudad de México, CDMX",
            "url" => "https://www.facebook.com/AlianzaDeTrabajadoresDeLaSaludYEmpleadosPublicos",
            "fone" => "",
        ),
)
?>